version: "3.1"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - mongodbdata:/data/db
    ports:
      - "27017:27017"
    networks:
      - dataplaynet
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
  mongo-express:
    profiles: [ "mongo", "user_data" ]
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - dataplaynet
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongo:27017/
      ME_CONFIG_BASICAUTH:


networks:
  dataplaynet:
    external: true

volumes:
  mongodbdata:
